# -*- coding: utf-8 -*-
"""ifrs17tookit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tBQjKLk6ZIhl6pBwx4wvaO8ST3KFP84J
"""

# =============================================================================
#  AFRICAN ACTUARIAL CONSULTANTS — COMPREHENSIVE ACTUARIAL TOOLKIT
#  Main App with Multi-Page Navigation
#  Theme: Light Blue (#4A90D9), Black, White
#  Run:  streamlit run app.py
# =============================================================================

import streamlit as st
import pandas as pd
import numpy as np
from io import BytesIO
from datetime import date
import re

# Must be the first Streamlit command
st.set_page_config(
    page_title="AAC Actuarial Toolkit",
    page_icon="📊",
    layout="wide",
    initial_sidebar_state="expanded"
)

# =============================================================================
#  CUSTOM CSS — AAC THEME: Light Blue (#4A90D9), Black (#000000), White (#FFFFFF)
# =============================================================================

st.markdown("""
<style>
    /* ========== GLOBAL STYLES ========== */
    .stApp {
        background-color: #FFFFFF;
        color: #000000;
        font-family: 'Calisto MT', 'Georgia', serif;
        font-size: 11pt;
    }

    h1, h2, h3, h4, h5, h6, p, div, span, label {
        font-family: 'Calisto MT', 'Georgia', serif !important;
    }

    /* ========== HEADER BAR ========== */
    .header {
        background-color: #000000;
        padding: 1rem 2rem;
        display: flex;
        align-items: center;
        justify-content: space-between;
        border-bottom: 3px solid #4A90D9;
    }
    .header .logo {
        color: #4A90D9;
        font-size: 1.5rem;
        font-weight: bold;
    }
    .nav-links a {
        color: #FFFFFF;
        margin-left: 2rem;
        text-decoration: none;
        font-weight: 500;
    }
    .nav-links a:hover { color: #4A90D9; }

    /* ========== HERO SECTION ========== */
    .hero {
        background: linear-gradient(135deg, #000000 0%, #1a1a2e 100%);
        color: #FFFFFF;
        padding: 3rem 2rem;
        text-align: center;
        border-bottom: 3px solid #4A90D9;
    }
    .hero h1 { color: #4A90D9; font-size: 2.8rem; margin-bottom: 0.5rem; }
    .hero p { font-size: 1.2rem; max-width: 800px; margin: 0 auto; }

    /* ========== CARDS ========== */
    .card {
        background-color: #F9F9F9;
        border: 1px solid #4A90D9;
        border-radius: 8px;
        padding: 1.5rem;
        box-shadow: 0 4px 6px rgba(0,0,0,0.1);
        margin-bottom: 1.5rem;
        text-align: center;
        transition: transform 0.2s;
    }
    .card:hover { transform: translateY(-3px); }
    .card h3 { color: #4A90D9; margin-top: 0; }

    /* ========== FOOTER ========== */
    .footer {
        background-color: #000000;
        color: #FFFFFF;
        text-align: center;
        padding: 1.5rem;
        border-top: 3px solid #4A90D9;
        margin-top: 3rem;
    }
    .footer a { color: #4A90D9; }

    /* ========== BUTTONS ========== */
    .stButton > button {
        background-color: #4A90D9 !important;
        color: #000000 !important;
        border: none !important;
        border-radius: 4px !important;
        font-weight: bold !important;
        padding: 0.75rem 1.5rem !important;
        width: 100% !important;
        font-family: 'Calisto MT', 'Georgia', serif !important;
    }
    .stButton > button:hover {
        background-color: #357ABD !important;
        color: #FFFFFF !important;
    }

    /* ========== SECTION CONTAINERS ========== */
    .section-container {
        background-color: #F9F9F9;
        border: 2px solid #4A90D9;
        border-radius: 10px;
        padding: 1.5rem;
        margin-bottom: 1.5rem;
    }
    .section-container h3 {
        color: #4A90D9;
        margin-top: 0;
        font-size: 1.2rem;
        font-weight: bold;
    }

    /* ========== BREADCRUMB ========== */
    .breadcrumb {
        background-color: #F0F0F0;
        padding: 0.5rem 1rem;
        border-radius: 5px;
        margin-bottom: 1rem;
        font-size: 0.9rem;
        border-left: 3px solid #4A90D9;
    }
    .breadcrumb span { color: #4A90D9; font-weight: bold; }

    /* ========== FILE UPLOADER ========== */
    .stFileUploader {
        border: 2px dashed #4A90D9 !important;
        border-radius: 10px !important;
        padding: 1rem !important;
    }

    /* ========== DATA QUALITY BOXES ========== */
    .data-check-info { background-color: #E3F2FD; border: 2px solid #4A90D9; border-radius: 10px; padding: 1rem; margin-bottom: 1rem; }
    .data-check-warning { background-color: #FFF3E0; border: 2px solid #FF9800; border-radius: 10px; padding: 1rem; margin-bottom: 1rem; }
    .data-check-error { background-color: #FFEBEE; border: 2px solid #F44336; border-radius: 10px; padding: 1rem; margin-bottom: 1rem; }
    .data-check-success { background-color: #E8F5E9; border: 2px solid #4CAF50; border-radius: 10px; padding: 1rem; margin-bottom: 1rem; }

    /* ========== DATAFRAME ========== */
    .dataframe { border: 1px solid #4A90D9 !important; border-radius: 8px !important; overflow: hidden !important; }

    /* ========== SELECT BOX ========== */
    .stSelectbox [data-baseweb="select"], .stMultiSelect [data-baseweb="select"] {
        border: 1px solid #4A90D9 !important;
        border-radius: 4px !important;
    }
</style>
""", unsafe_allow_html=True)

# =============================================================================
#  SESSION STATE FOR NAVIGATION
# =============================================================================

if 'page' not in st.session_state:
    st.session_state.page = 'home'

if 'breadcrumb' not in st.session_state:
    st.session_state.breadcrumb = ['Home']

# =============================================================================
#  NAVIGATION FUNCTIONS
# =============================================================================

def navigate_to(page, breadcrumb_label=None):
    """Navigate to a page and update breadcrumb."""
    st.session_state.page = page
    if breadcrumb_label:
        st.session_state.breadcrumb = breadcrumb_label

def go_home():
    st.session_state.page = 'home'
    st.session_state.breadcrumb = ['Home']

# =============================================================================
#  HEADER
# =============================================================================

st.markdown("""
<div class="header">
    <div class="logo">◆ AAC Actuarial Toolkit</div>
    <div class="nav-links">
        <a href="javascript:void(0)" onclick="window.location.reload()">Home</a>
    </div>
</div>
""", unsafe_allow_html=True)

# =============================================================================
#  BREADCRUMB DISPLAY
# =============================================================================

def show_breadcrumb():
    if len(st.session_state.breadcrumb) > 1 or st.session_state.breadcrumb[0] != 'Home':
        breadcrumb_html = " > ".join(
            [f"<span>{b}</span>" for b in st.session_state.breadcrumb]
        )
        st.markdown(f'<div class="breadcrumb">📍 {breadcrumb_html}</div>', unsafe_allow_html=True)

# =============================================================================
#  BACK BUTTON HELPER
# =============================================================================

def back_button(target_page, target_breadcrumb):
    """Standardized back button."""
    st.markdown("<br>", unsafe_allow_html=True)
    if st.button("← Back", key=f"back_{target_page}"):
        navigate_to(target_page, target_breadcrumb)
        st.rerun()

# =============================================================================
#  PAGE RENDERERS
# =============================================================================

def render_home():
    """Main welcome page."""
    st.markdown("""
    <div class="hero">
        <h1>African Actuarial Consultants</h1>
        <p>Comprehensive Actuarial Reserving Toolkit — IFRS 17 Compliant</p>
        <p style="margin-top: 1rem; font-size: 1rem;">Liability for Remaining Coverage (LRC) | Liability for Incurred Claims (LIC)</p>
    </div>
    """, unsafe_allow_html=True)

    st.markdown("<br>", unsafe_allow_html=True)

    col1, col2 = st.columns(2)

    with col1:
        st.markdown("""
        <div class="card">
            <h3>📋 LRC — Liability for Remaining Coverage</h3>
            <p>Unexpired risk reserve calculations for premium liabilities.</p>
            <p style="font-size:0.85rem;color:#666;">UPR Calculator | Loss Component</p>
        </div>
        """, unsafe_allow_html=True)
        if st.button("Go to LRC Calculators", key="btn_lrc"):
            navigate_to('lrc', ['Home', 'LRC'])
            st.rerun()

    with col2:
        st.markdown("""
        <div class="card">
            <h3>📊 LIC — Liability for Incurred Claims</h3>
            <p>Outstanding claims reserves, IBNR, ULAE, Risk Adjustment, and more.</p>
            <p style="font-size:0.85rem;color:#666;">Fulfilment Cashflows | Risk Adjustment</p>
        </div>
        """, unsafe_allow_html=True)
        if st.button("Go to LIC Calculators", key="btn_lic"):
            navigate_to('lic', ['Home', 'LIC'])
            st.rerun()

    st.markdown("<br><br>", unsafe_allow_html=True)
    st.info("Select LRC or LIC above to access the relevant actuarial calculators.")


def render_lrc():
    """LRC — Liability for Remaining Coverage page."""
    show_breadcrumb()

    st.markdown("""
    <div class="hero" style="padding: 2rem;">
        <h1>LRC — Liability for Remaining Coverage</h1>
        <p>Unexpired risk reserve and loss component calculations</p>
    </div>
    """, unsafe_allow_html=True)

    col1, col2 = st.columns(2)

    with col1:
        st.markdown('<div class="card"><h3>📈 UPR Calculator</h3><p>Unearned Premium Reserve — 365th, 24th, and 8th methods with data quality checks.</p></div>', unsafe_allow_html=True)
        if st.button("Open UPR Calculator", key="btn_upr"):
            navigate_to('upr_calculator', ['Home', 'LRC', 'UPR Calculator'])
            st.rerun()

    with col2:
        st.markdown('<div class="card"><h3>📉 Loss Component</h3><p>Calculate Loss Ratio, Commission Ratio, Expense Ratio, Combined Ratio, and Loss Component.</p></div>', unsafe_allow_html=True)
        if st.button("Open Loss Component", key="btn_loss_comp"):
            navigate_to('loss_component', ['Home', 'LRC', 'Loss Component'])
            st.rerun()

    back_button('home', ['Home'])


def render_lic():
    """LIC — Liability for Incurred Claims page."""
    show_breadcrumb()

    st.markdown("""
    <div class="hero" style="padding: 2rem;">
        <h1>LIC — Liability for Incurred Claims</h1>
        <p>Outstanding claims, IBNR, ULAE, NPR, and Risk Adjustment</p>
    </div>
    """, unsafe_allow_html=True)

    col1, col2 = st.columns(2)

    with col1:
        st.markdown('<div class="card"><h3>💰 Fulfilment Cashflows</h3><p>OCR, IBNR (6 methods), ULAE, and NPR calculators.</p></div>', unsafe_allow_html=True)
        if st.button("Fulfilment Cashflows →", key="btn_fulfilment"):
            navigate_to('fulfilment_cashflows', ['Home', 'LIC', 'Fulfilment Cashflows'])
            st.rerun()

    with col2:
        st.markdown('<div class="card"><h3>🎯 Risk Adjustment</h3><p>Mack, Bootstrap, VaR, and Cost of Capital methods.</p></div>', unsafe_allow_html=True)
        if st.button("Risk Adjustment →", key="btn_ra"):
            navigate_to('risk_adjustment', ['Home', 'LIC', 'Risk Adjustment'])
            st.rerun()

    back_button('home', ['Home'])


def render_fulfilment_cashflows():
    """Fulfilment Cashflows sub-menu."""
    show_breadcrumb()

    st.markdown("## 💰 Fulfilment Cashflows")
    st.markdown("Select a calculator from the options below:")
    st.markdown("<br>", unsafe_allow_html=True)

    cols = st.columns(4)
    calculators = [
        ("📋 OCR", "Outstanding Claims Reserve", "ocr_calculator", "OCR Calculator"),
        ("📊 IBNR", "Incurred But Not Reported — 6 Methods", "ibnr_menu", "IBNR Methods"),
        ("💸 ULAE", "Unallocated Loss Adjustment Expenses", "ulae_calculator", "ULAE Calculator"),
        ("🔒 NPR", "Non-Performance Risk (Reinsurance)", "npr_calculator", "NPR Calculator"),
    ]

    for i, (title, desc, page, breadcrumb) in enumerate(calculators):
        with cols[i]:
            st.markdown(f'<div class="card"><h3>{title}</h3><p>{desc}</p></div>', unsafe_allow_html=True)
            if st.button(f"Open", key=f"btn_{page}"):
                navigate_to(page, ['Home', 'LIC', 'Fulfilment Cashflows', breadcrumb])
                st.rerun()

    back_button('lic', ['Home', 'LIC'])


def render_ibnr_menu():
    """IBNR Methods sub-menu."""
    show_breadcrumb()

    st.markdown("## 📊 IBNR Calculation Methods")
    st.markdown("Select an IBNR estimation method:")
    st.markdown("<br>", unsafe_allow_html=True)

    methods = [
        ("📈 Percentage Approach", "Simple percentage of premiums", "ibnr_percentage"),
        ("📐 Basic Chain Ladder (BCL)", "Traditional CL with inflation & discounting", "bcl_calculator"),
        ("🎣 Cape Cod", "Internally-derived loss ratio from used-up premium", "capecod_calculator"),
        ("🎯 Bornhuetter-Ferguson (BF)", "A-priori ELR with development pattern", "bf_calculator"),
        ("📋 Expected Loss Ratio (ELR)", "Pure ELR method for IBNR", "elr_calculator"),
        ("📎 Average Cost Per Claim (ACPC)", "Claims frequency & severity approach", "acpc_calculator"),
    ]

    for i in range(0, len(methods), 3):
        cols = st.columns(3)
        for j in range(3):
            idx = i + j
            if idx < len(methods):
                name, desc, page = methods[idx]
                with cols[j]:
                    st.markdown(f'<div class="card"><h3>{name}</h3><p>{desc}</p></div>', unsafe_allow_html=True)
                    if st.button(f"Open {name.split(' ')[0]}", key=f"btn_{page}"):
                        navigate_to(page, ['Home', 'LIC', 'Fulfilment Cashflows', 'IBNR Methods', name.split(' ')[0]])
                        st.rerun()

    back_button('fulfilment_cashflows', ['Home', 'LIC', 'Fulfilment Cashflows'])


def render_risk_adjustment():
    """Risk Adjustment sub-menu."""
    show_breadcrumb()

    st.markdown("## 🎯 Risk Adjustment Methods")
    st.markdown("Select a risk adjustment methodology:")
    st.markdown("<br>", unsafe_allow_html=True)

    methods = [
        ("📐 Mack Method", "Distribution-free standard error of Chain Ladder", "mack_calculator"),
        ("🎲 Bootstrap", "England & Verrall (2002) stochastic reserving", "bootstrap_calculator"),
        ("📊 Value at Risk (VaR)", "Percentile-based risk measure", "var_calculator"),
        ("💰 Cost of Capital", "Solvency II cost of capital approach", "coc_calculator"),
    ]

    cols = st.columns(4)
    for i, (name, desc, page) in enumerate(methods):
        with cols[i]:
            st.markdown(f'<div class="card"><h3>{name}</h3><p>{desc}</p></div>', unsafe_allow_html=True)
            if st.button(f"Open", key=f"btn_{page}"):
                navigate_to(page, ['Home', 'LIC', 'Risk Adjustment', name.split(' ')[0]])
                st.rerun()

    back_button('lic', ['Home', 'LIC'])


# =============================================================================
#  ╔══════════════════════════════════════════════════════════════════════════╗
#  ║  CALCULATOR IMPLEMENTATIONS — INSERT YOUR CODE BELOW                    ║
#  ║  Each function contains the full Streamlit calculator code              ║
#  ╚══════════════════════════════════════════════════════════════════════════╝
# =============================================================================


# =============================================================================
#  LRC CALCULATORS
# =============================================================================

def render_upr_calculator():
    """UPR Calculator."""
    show_breadcrumb()
    st.markdown("## 📈 UPR Calculator — Unearned Premium Reserve")

    # ╔══════════════════════════════════════════════════════════════════════╗
    # ║  INSERT YOUR UPR CALCULATOR CODE HERE                               ║
    # ║  Copy the entire Streamlit UPR calculator code starting from:       ║
    # ║  - Client name input                                                ║
    # ║  - File uploader                                                    ║
    # ║  - Column mapping                                                   ║
    # ║  - Calculation logic                                                ║
    # ║  - Results display & Excel export                                   ║
    # ╚══════════════════════════════════════════════════════════════════════╝

    st.info("UPR Calculator — Insert your implementation here")
    back_button('lrc', ['Home', 'LRC'])


def render_loss_component():
    """Loss Component Calculator."""
    show_breadcrumb()
    st.markdown("## 📉 Loss Component Calculator")

    # ╔══════════════════════════════════════════════════════════════════════╗
    # ║  INSERT YOUR LOSS COMPONENT CALCULATOR CODE HERE                    ║
    # ╚══════════════════════════════════════════════════════════════════════╝

    st.info("Loss Component Calculator — Insert your implementation here")
    back_button('lrc', ['Home', 'LRC'])


# =============================================================================
#  FULFILMENT CASHFLOWS CALCULATORS
# =============================================================================

def render_ocr_calculator():
    """OCR Calculator."""
    show_breadcrumb()
    st.markdown("## 📋 OCR — Outstanding Claims Reserve Calculator")

    # ╔══════════════════════════════════════════════════════════════════════╗
    # ║  INSERT YOUR OCR CALCULATOR CODE HERE                               ║
    # ║  This is the "Outstanding Claims Reserve (OCR) Calculator"          ║
    # ║  - File upload                                                      ║
    # ║  - Grouping columns selection                                       ║
    # ║  - Numeric columns selection                                        ║
    # ║  - Data quality checks                                              ║
    # ║  - Grouped sum results                                              ║
    # ║  - Excel export                                                     ║
    # ╚══════════════════════════════════════════════════════════════════════╝

    st.info("OCR Calculator — Insert your implementation here")
    back_button('fulfilment_cashflows', ['Home', 'LIC', 'Fulfilment Cashflows'])


def render_ibnr_percentage():
    """IBNR Percentage Method."""
    show_breadcrumb()
    st.markdown("## 📈 IBNR Percentage Method Calculator")

    # ╔══════════════════════════════════════════════════════════════════════╗
    # ║  INSERT YOUR IBNR PERCENTAGE METHOD CODE HERE                       ║
    # ║  This is the "IBNR Calculator: Percentage Method"                   ║
    # ║  - Client name                                                      ║
    # ║  - Date range                                                       ║
    # ║  - IBNR percentage input                                            ║
    # ║  - File upload                                                      ║
    # ║  - Column mapping (Date, LOB, Amount)                              ║
    # ║  - Data quality checks                                              ║
    # ║  - IBNR calculation                                                 ║
    # ║  - Excel export                                                     ║
    # ╚══════════════════════════════════════════════════════════════════════╝

    st.info("IBNR Percentage Method — Insert your implementation here")
    back_button('ibnr_menu', ['Home', 'LIC', 'Fulfilment Cashflows', 'IBNR Methods'])


def render_bcl_calculator():
    """Basic Chain Ladder Calculator."""
    show_breadcrumb()
    st.markdown("## 📐 Basic Chain Ladder (BCL) IBNR Calculator")

    # ╔══════════════════════════════════════════════════════════════════════╗
    # ║  INSERT YOUR BCL CALCULATOR CODE HERE                               ║
    # ║  This is the "ADVANCED CHAIN LADDER IBNR CALCULATOR"               ║
    # ║  Features:                                                          ║
    # ║  - Client name                                                      ║
    # ║  - Claims file upload                                               ║
    # ║  - Column mapping (Loss_Date, Report_Date, Amount, Grouping)       ║
    # ║  - Date range & Grain selection                                     ║
    # ║  - Discounting (Yield curve or single rate)                         ║
    # ║  - Inflation adjustment                                             ║
    # ║  - LDF selection (6 methods) with stability diagnostics            ║
    # ║  - IBNR calculation & Excel export                                  ║
    # ╚══════════════════════════════════════════════════════════════════════╝

    st.info("Basic Chain Ladder — Insert your implementation here")
    back_button('ibnr_menu', ['Home', 'LIC', 'Fulfilment Cashflows', 'IBNR Methods'])


def render_capecod_calculator():
    """Cape Cod Calculator."""
    show_breadcrumb()
    st.markdown("## 🎣 Cape Cod IBNR Calculator")

    # ╔══════════════════════════════════════════════════════════════════════╗
    # ║  INSERT YOUR CAPE COD CALCULATOR CODE HERE                          ║
    # ╚══════════════════════════════════════════════════════════════════════╝

    st.info("Cape Cod — Insert your implementation here")
    back_button('ibnr_menu', ['Home', 'LIC', 'Fulfilment Cashflows', 'IBNR Methods'])


def render_bf_calculator():
    """Bornhuetter-Ferguson Calculator."""
    show_breadcrumb()
    st.markdown("## 🎯 Bornhuetter-Ferguson (BF) IBNR Calculator")

    # ╔══════════════════════════════════════════════════════════════════════╗
    # ║  INSERT YOUR BF CALCULATOR CODE HERE                                ║
    # ╚══════════════════════════════════════════════════════════════════════╝

    st.info("Bornhuetter-Ferguson — Insert your implementation here")
    back_button('ibnr_menu', ['Home', 'LIC', 'Fulfilment Cashflows', 'IBNR Methods'])


def render_elr_calculator():
    """Expected Loss Ratio Calculator."""
    show_breadcrumb()
    st.markdown("## 📋 Expected Loss Ratio (ELR) IBNR Calculator")

    # ╔══════════════════════════════════════════════════════════════════════╗
    # ║  INSERT YOUR ELR CALCULATOR CODE HERE                               ║
    # ╚══════════════════════════════════════════════════════════════════════╝

    st.info("Expected Loss Ratio — Insert your implementation here")
    back_button('ibnr_menu', ['Home', 'LIC', 'Fulfilment Cashflows', 'IBNR Methods'])


def render_acpc_calculator():
    """Average Cost Per Claim Calculator."""
    show_breadcrumb()
    st.markdown("## 📎 Average Cost Per Claim (ACPC) IBNR Calculator")

    # ╔══════════════════════════════════════════════════════════════════════╗
    # ║  INSERT YOUR ACPC CALCULATOR CODE HERE                              ║
    # ╚══════════════════════════════════════════════════════════════════════╝

    st.info("Average Cost Per Claim — Insert your implementation here")
    back_button('ibnr_menu', ['Home', 'LIC', 'Fulfilment Cashflows', 'IBNR Methods'])


def render_ulae_calculator():
    """ULAE Calculator."""
    show_breadcrumb()
    st.markdown("## 💸 ULAE — Unallocated Loss Adjustment Expenses Calculator")

    # ╔══════════════════════════════════════════════════════════════════════╗
    # ║  INSERT YOUR ULAE CALCULATOR CODE HERE                              ║
    # ║  Features:                                                          ║
    # ║  - Reserves data (Detailed OCR+IBNR or Summary)                     ║
    # ║  - Calculation basis (Per Portfolio or Aggregated)                  ║
    # ║  - Apportionment data (for aggregated)                              ║
    # ║  - ULAE ratio (Overall, Per Portfolio Manual, Per Portfolio File)   ║
    # ║  - ULAE calculation & Excel export                                  ║
    # ╚══════════════════════════════════════════════════════════════════════╝

    st.info("ULAE Calculator — Insert your implementation here")
    back_button('fulfilment_cashflows', ['Home', 'LIC', 'Fulfilment Cashflows'])


def render_npr_calculator():
    """NPR Calculator."""
    show_breadcrumb()
    st.markdown("## 🔒 NPR — Non-Performance Risk (Reinsurance) Calculator")

    # ╔══════════════════════════════════════════════════════════════════════╗
    # ║  INSERT YOUR NPR CALCULATOR CODE HERE                               ║
    # ╚══════════════════════════════════════════════════════════════════════╝

    st.info("NPR Calculator — Insert your implementation here")
    back_button('fulfilment_cashflows', ['Home', 'LIC', 'Fulfilment Cashflows'])


# =============================================================================
#  RISK ADJUSTMENT CALCULATORS
# =============================================================================

def render_mack_calculator():
    """Mack Method Calculator."""
    show_breadcrumb()
    st.markdown("## 📐 Mack Method — Risk Adjustment Calculator")

    # ╔══════════════════════════════════════════════════════════════════════╗
    # ║  INSERT YOUR MACK METHOD CODE HERE                                  ║
    # ╚══════════════════════════════════════════════════════════════════════╝

    st.info("Mack Method — Insert your implementation here")
    back_button('risk_adjustment', ['Home', 'LIC', 'Risk Adjustment'])


def render_bootstrap_calculator():
    """Bootstrap Calculator."""
    show_breadcrumb()
    st.markdown("## 🎲 Bootstrap — Stochastic Reserving Calculator")

    # ╔══════════════════════════════════════════════════════════════════════╗
    # ║  INSERT YOUR BOOTSTRAP CALCULATOR CODE HERE                         ║
    # ║  This is the "STANDARD BOOTSTRAP CHAIN LADDER IBNR CALCULATOR"     ║
    # ║  Features:                                                          ║
    # ║  - Claims file upload                                               ║
    # ║  - Column mapping                                                   ║
    # ║  - Date range & Grain                                               ║
    # ║  - Discounting & Inflation                                          ║
    # ║  - Bootstrap parameters (iterations, process variance, seed)       ║
    # ║  - Confidence levels & RA calculation                              ║
    # ║  - Simulated IBNR distribution                                      ║
    # ║  - Excel export with samples                                        ║
    # ╚══════════════════════════════════════════════════════════════════════╝

    st.info("Bootstrap — Insert your implementation here")
    back_button('risk_adjustment', ['Home', 'LIC', 'Risk Adjustment'])


def render_var_calculator():
    """Value at Risk Calculator."""
    show_breadcrumb()
    st.markdown("## 📊 Value at Risk (VaR) — Risk Adjustment Calculator")

    # ╔══════════════════════════════════════════════════════════════════════╗
    # ║  INSERT YOUR VAR CALCULATOR CODE HERE                               ║
    # ╚══════════════════════════════════════════════════════════════════════╝

    st.info("Value at Risk — Insert your implementation here")
    back_button('risk_adjustment', ['Home', 'LIC', 'Risk Adjustment'])


def render_coc_calculator():
    """Cost of Capital Calculator."""
    show_breadcrumb()
    st.markdown("## 💰 Cost of Capital — Risk Adjustment Calculator")

    # ╔══════════════════════════════════════════════════════════════════════╗
    # ║  INSERT YOUR COST OF CAPITAL CODE HERE                              ║
    # ╚══════════════════════════════════════════════════════════════════════╝

    st.info("Cost of Capital — Insert your implementation here")
    back_button('risk_adjustment', ['Home', 'LIC', 'Risk Adjustment'])


# =============================================================================
#  MAIN ROUTER — Maps page names to renderer functions
# =============================================================================

page_renderers = {
    # Main navigation
    'home':                    render_home,
    'lrc':                     render_lrc,
    'lic':                     render_lic,
    'fulfilment_cashflows':    render_fulfilment_cashflows,
    'ibnr_menu':               render_ibnr_menu,
    'risk_adjustment':         render_risk_adjustment,

    # LRC Calculators
    'upr_calculator':          render_upr_calculator,
    'loss_component':          render_loss_component,

    # Fulfilment Cashflows Calculators
    'ocr_calculator':          render_ocr_calculator,
    'ibnr_percentage':         render_ibnr_percentage,
    'bcl_calculator':          render_bcl_calculator,
    'capecod_calculator':      render_capecod_calculator,
    'bf_calculator':           render_bf_calculator,
    'elr_calculator':          render_elr_calculator,
    'acpc_calculator':         render_acpc_calculator,
    'ulae_calculator':         render_ulae_calculator,
    'npr_calculator':          render_npr_calculator,

    # Risk Adjustment Calculators
    'mack_calculator':         render_mack_calculator,
    'bootstrap_calculator':    render_bootstrap_calculator,
    'var_calculator':          render_var_calculator,
    'coc_calculator':          render_coc_calculator,
}

# Render the current page
current_page = st.session_state.page
if current_page in page_renderers:
    page_renderers[current_page]()
else:
    render_home()

# =============================================================================
#  FOOTER
# =============================================================================

st.markdown("""
<div class="footer">
    <p>© 2026 African Actuarial Consultants. All rights reserved.</p>
    <p style="margin-top: 0.5rem; font-size: 0.9rem;">IFRS 17 Compliant | Solvency II Ready | Built with ❤️ by AAC</p>
</div>
""", unsafe_allow_html=True)